CountryBlocker:
  announcement: "<hover:show_text:\"<blue>CountryBlocker: <white><user>\n<gray>IPAddress: <gold><ip>\n<dark_green>Country: <white><country>\n<gold>Time: <white><time>\"><gray>User <user> trying connect on this server from <country>"
  deny_message: "<gray>Your country <yellow><connected_country> <gray>was blocked on this server !"
  blockList:
    - RU